//
//  File.swift
//
//
//  Created by Tomislav Markovski on 11/30/21.
//

import Foundation
import GRPC

public class TrustRegistryService: ServiceBase {
    var client: Services_Trustregistry_V1_TrustRegistryNIOClient?

    public init() {
        super.init(options: Sdk_Options_V1_ServiceOptions())
        client = Services_Trustregistry_V1_TrustRegistryNIOClient(channel: createChannel())
    }

    override public init(options: Sdk_Options_V1_ServiceOptions) {
        super.init(options: options)
        client = Services_Trustregistry_V1_TrustRegistryNIOClient(channel: createChannel())
    }

    // BEGIN Code generated by protoc-gen-trinsic. DO NOT EDIT.
    // target: /Users/scott/Documents/GitHub/sdk-swift/Sources/Trinsic/TrustRegistryService.swift

    public func addFramework(request: Services_Trustregistry_V1_AddFrameworkRequest) throws -> Services_Trustregistry_V1_AddFrameworkResponse {
        try client!.AddFramework(request, callOptions: buildMetadata(request))
            .response
            .wait()
    }

    public func removeFramework(request: Services_Trustregistry_V1_RemoveFrameworkRequest) throws -> Services_Trustregistry_V1_RemoveFrameworkResponse {
        try client!.RemoveFramework(request, callOptions: buildMetadata(request))
            .response
            .wait()
    }

    public func searchRegistry(request: Services_Trustregistry_V1_SearchRegistryRequest) throws -> Services_Trustregistry_V1_SearchRegistryResponse {
        try client!.SearchRegistry(request, callOptions: buildMetadata(request))
            .response
            .wait()
    }

    public func registerMember(request: Services_Trustregistry_V1_RegisterMemberRequest) throws -> Services_Trustregistry_V1_RegisterMemberResponse {
        try client!.RegisterMember(request, callOptions: buildMetadata(request))
            .response
            .wait()
    }

    public func unregisterMember(request: Services_Trustregistry_V1_UnregisterMemberRequest) throws -> Services_Trustregistry_V1_UnregisterMemberResponse {
        try client!.UnregisterMember(request, callOptions: buildMetadata(request))
            .response
            .wait()
    }

    public func getMembershipStatus(request: Services_Trustregistry_V1_GetMembershipStatusRequest) throws -> Services_Trustregistry_V1_GetMembershipStatusResponse {
        try client!.GetMembershipStatus(request, callOptions: buildMetadata(request))
            .response
            .wait()
    }
    // END Code generated by protoc-gen-trinsic. DO NOT EDIT.
}
