//
//  File.swift
//
//
//  Created by Tomislav Markovski on 11/30/21.
//

import Foundation
import GRPC

public class WalletService: ServiceBase {
    var client: Services_Universalwallet_V1_UniversalWalletNIOClient?

    public init() {
        super.init(options: Sdk_Options_V1_ServiceOptions())
        client = Services_Universalwallet_V1_UniversalWalletNIOClient(channel: createChannel())
    }

    override public init(options: Sdk_Options_V1_ServiceOptions) {
        super.init(options: options)
        client = Services_Universalwallet_V1_UniversalWalletNIOClient(channel: createChannel())
    }

    public func search() throws -> Services_Universalwallet_V1_SearchResponse {
        try search(request: Services_Universalwallet_V1_SearchRequest())
    }

    public func searchWallet(request: Services_Universalwallet_V1_SearchRequest = Services_Universalwallet_V1_SearchRequest()) throws -> Services_Universalwallet_V1_SearchResponse {
        var request = request
        if request.query.isEmpty {
            request.query = "SELECT c.id, c.type, c.data FROM c OFFSET 0 LIMIT 100"
        }
        return try client!.Search(request, callOptions: try buildMetadata(request))
            .response
            .wait()
    }

    // BEGIN Code generated by protoc-gen-trinsic. DO NOT EDIT.
    // target: /Users/scott/Documents/GitHub/sdk-swift/Sources/Trinsic/WalletService.swift

    public func getItem(request: Services_Universalwallet_V1_GetItemRequest) throws -> Services_Universalwallet_V1_GetItemResponse {
        try client!.GetItem(request, callOptions: try buildMetadata(request))
            .response
            .wait()
    }

    public func search(request: Services_Universalwallet_V1_SearchRequest) throws -> Services_Universalwallet_V1_SearchResponse {
        try client!.Search(request, callOptions: try buildMetadata(request))
            .response
            .wait()
    }

    public func insertItem(request: Services_Universalwallet_V1_InsertItemRequest) throws -> Services_Universalwallet_V1_InsertItemResponse {
        try client!.InsertItem(request, callOptions: try buildMetadata(request))
            .response
            .wait()
    }

    public func updateItem(request: Services_Universalwallet_V1_UpdateItemRequest) throws -> Services_Universalwallet_V1_UpdateItemResponse {
        try client!.UpdateItem(request, callOptions: try buildMetadata(request))
            .response
            .wait()
    }

    public func deleteItem(request: Services_Universalwallet_V1_DeleteItemRequest) throws -> Services_Universalwallet_V1_DeleteItemResponse {
        try client!.DeleteItem(request, callOptions: try buildMetadata(request))
            .response
            .wait()
    }

    public func deleteWallet(request: Services_Universalwallet_V1_DeleteWalletRequest) throws -> Services_Universalwallet_V1_DeleteWalletResponse {
        try client!.DeleteWallet(request, callOptions: try buildMetadata(request))
            .response
            .wait()
    }
    // END Code generated by protoc-gen-trinsic. DO NOT EDIT.
}
