
// BEGIN Doc Code generated by protoc-gen-trinsic. DO NOT EDIT.
// target: C:\work\sdk-swift\Tests\TrinsicTests\credentialtemplates_service_examples.swift

// createCredentialTemplatesService() {
// }

// credentialTemplatesCreate() {
// }

// credentialTemplatesGet() {
// }

// credentialTemplatesUpdate() {
// }

// credentialTemplatesList() {
// }

// credentialTemplatesSearch() {
// }

// credentialTemplatesDelete() {
// }

// END Doc Code generated by protoc-gen-trinsic. DO NOT EDIT.