
// BEGIN Doc Code generated by protoc-gen-trinsic. DO NOT EDIT.
// target: C:\work\sdk-swift\Tests\TrinsicTests\filemanagement_service_examples.swift

// createFileManagementService() {
// }

// fileManagementUploadFile() {
// }

// fileManagementGetFile() {
// }

// fileManagementDeleteFile() {
// }

// fileManagementListFiles() {
// }

// fileManagementGetStorageStats() {
// }

// END Doc Code generated by protoc-gen-trinsic. DO NOT EDIT.