
// BEGIN Doc Code generated by protoc-gen-trinsic. DO NOT EDIT.
// target: C:\work\sdk-swift\Tests\TrinsicTests\verifiablecredential_service_examples.swift

// createVerifiableCredentialService() {
// }

// verifiableCredentialIssue() {
// }

// verifiableCredentialIssueFromTemplate() {
// }

// verifiableCredentialCheckStatus() {
// }

// verifiableCredentialUpdateStatus() {
// }

// verifiableCredentialCreateProof() {
// }

// verifiableCredentialVerifyProof() {
// }

// verifiableCredentialSend() {
// }

// END Doc Code generated by protoc-gen-trinsic. DO NOT EDIT.