//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: services/trust-registry/v1/trust-registry.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import GRPC
import NIO
import SwiftProtobuf


/// Usage: instantiate `Services_Trustregistry_V1_TrustRegistryClient`, then call methods of this protocol to make API calls.
public protocol Services_Trustregistry_V1_TrustRegistryClientProtocol: GRPCClient {
  var serviceName: String { get }
  var interceptors: Services_Trustregistry_V1_TrustRegistryClientInterceptorFactoryProtocol? { get }

  func AddFramework(
    _ request: Services_Trustregistry_V1_AddFrameworkRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Services_Trustregistry_V1_AddFrameworkRequest, Services_Trustregistry_V1_AddFrameworkResponse>

  func RemoveFramework(
    _ request: Services_Trustregistry_V1_RemoveFrameworkRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Services_Trustregistry_V1_RemoveFrameworkRequest, Services_Trustregistry_V1_RemoveFrameworkResponse>

  func SearchRegistry(
    _ request: Services_Trustregistry_V1_SearchRegistryRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Services_Trustregistry_V1_SearchRegistryRequest, Services_Trustregistry_V1_SearchRegistryResponse>

  func RegisterIssuer(
    _ request: Services_Trustregistry_V1_RegisterIssuerRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Services_Trustregistry_V1_RegisterIssuerRequest, Services_Trustregistry_V1_RegisterIssuerResponse>

  func RegisterVerifier(
    _ request: Services_Trustregistry_V1_RegisterVerifierRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Services_Trustregistry_V1_RegisterVerifierRequest, Services_Trustregistry_V1_RegisterVerifierResponse>

  func UnregisterIssuer(
    _ request: Services_Trustregistry_V1_UnregisterIssuerRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Services_Trustregistry_V1_UnregisterIssuerRequest, Services_Trustregistry_V1_UnregisterIssuerResponse>

  func UnregisterVerifier(
    _ request: Services_Trustregistry_V1_UnregisterVerifierRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Services_Trustregistry_V1_UnregisterVerifierRequest, Services_Trustregistry_V1_UnregisterVerifierResponse>

  func CheckIssuerStatus(
    _ request: Services_Trustregistry_V1_CheckIssuerStatusRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Services_Trustregistry_V1_CheckIssuerStatusRequest, Services_Trustregistry_V1_CheckIssuerStatusResponse>

  func CheckVerifierStatus(
    _ request: Services_Trustregistry_V1_CheckVerifierStatusRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Services_Trustregistry_V1_CheckVerifierStatusRequest, Services_Trustregistry_V1_CheckVerifierStatusResponse>

  func FetchData(
    _ request: Services_Trustregistry_V1_FetchDataRequest,
    callOptions: CallOptions?,
    handler: @escaping (Services_Trustregistry_V1_FetchDataResponse) -> Void
  ) -> ServerStreamingCall<Services_Trustregistry_V1_FetchDataRequest, Services_Trustregistry_V1_FetchDataResponse>
}

extension Services_Trustregistry_V1_TrustRegistryClientProtocol {
  public var serviceName: String {
    return "services.trustregistry.v1.TrustRegistry"
  }

  /// Adds a trust registry defintion to the ecosystem
  ///
  /// - Parameters:
  ///   - request: Request to send to AddFramework.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func AddFramework(
    _ request: Services_Trustregistry_V1_AddFrameworkRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Services_Trustregistry_V1_AddFrameworkRequest, Services_Trustregistry_V1_AddFrameworkResponse> {
    return self.makeUnaryCall(
      path: "/services.trustregistry.v1.TrustRegistry/AddFramework",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeAddFrameworkInterceptors() ?? []
    )
  }

  /// Unary call to RemoveFramework
  ///
  /// - Parameters:
  ///   - request: Request to send to RemoveFramework.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func RemoveFramework(
    _ request: Services_Trustregistry_V1_RemoveFrameworkRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Services_Trustregistry_V1_RemoveFrameworkRequest, Services_Trustregistry_V1_RemoveFrameworkResponse> {
    return self.makeUnaryCall(
      path: "/services.trustregistry.v1.TrustRegistry/RemoveFramework",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeRemoveFrameworkInterceptors() ?? []
    )
  }

  /// Unary call to SearchRegistry
  ///
  /// - Parameters:
  ///   - request: Request to send to SearchRegistry.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func SearchRegistry(
    _ request: Services_Trustregistry_V1_SearchRegistryRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Services_Trustregistry_V1_SearchRegistryRequest, Services_Trustregistry_V1_SearchRegistryResponse> {
    return self.makeUnaryCall(
      path: "/services.trustregistry.v1.TrustRegistry/SearchRegistry",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeSearchRegistryInterceptors() ?? []
    )
  }

  /// Registers an authoritative issuer with a credential template
  ///
  /// - Parameters:
  ///   - request: Request to send to RegisterIssuer.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func RegisterIssuer(
    _ request: Services_Trustregistry_V1_RegisterIssuerRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Services_Trustregistry_V1_RegisterIssuerRequest, Services_Trustregistry_V1_RegisterIssuerResponse> {
    return self.makeUnaryCall(
      path: "/services.trustregistry.v1.TrustRegistry/RegisterIssuer",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeRegisterIssuerInterceptors() ?? []
    )
  }

  /// Registers an authoritative verifier with a credential template
  ///
  /// - Parameters:
  ///   - request: Request to send to RegisterVerifier.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func RegisterVerifier(
    _ request: Services_Trustregistry_V1_RegisterVerifierRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Services_Trustregistry_V1_RegisterVerifierRequest, Services_Trustregistry_V1_RegisterVerifierResponse> {
    return self.makeUnaryCall(
      path: "/services.trustregistry.v1.TrustRegistry/RegisterVerifier",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeRegisterVerifierInterceptors() ?? []
    )
  }

  /// Removes an authoritative issuer with a credential template from the trust registry
  ///
  /// - Parameters:
  ///   - request: Request to send to UnregisterIssuer.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func UnregisterIssuer(
    _ request: Services_Trustregistry_V1_UnregisterIssuerRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Services_Trustregistry_V1_UnregisterIssuerRequest, Services_Trustregistry_V1_UnregisterIssuerResponse> {
    return self.makeUnaryCall(
      path: "/services.trustregistry.v1.TrustRegistry/UnregisterIssuer",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeUnregisterIssuerInterceptors() ?? []
    )
  }

  /// Removes an authoritative verifier with a presentation template from the trust registry
  ///
  /// - Parameters:
  ///   - request: Request to send to UnregisterVerifier.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func UnregisterVerifier(
    _ request: Services_Trustregistry_V1_UnregisterVerifierRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Services_Trustregistry_V1_UnregisterVerifierRequest, Services_Trustregistry_V1_UnregisterVerifierResponse> {
    return self.makeUnaryCall(
      path: "/services.trustregistry.v1.TrustRegistry/UnregisterVerifier",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeUnregisterVerifierInterceptors() ?? []
    )
  }

  /// Unary call to CheckIssuerStatus
  ///
  /// - Parameters:
  ///   - request: Request to send to CheckIssuerStatus.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func CheckIssuerStatus(
    _ request: Services_Trustregistry_V1_CheckIssuerStatusRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Services_Trustregistry_V1_CheckIssuerStatusRequest, Services_Trustregistry_V1_CheckIssuerStatusResponse> {
    return self.makeUnaryCall(
      path: "/services.trustregistry.v1.TrustRegistry/CheckIssuerStatus",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeCheckIssuerStatusInterceptors() ?? []
    )
  }

  /// Unary call to CheckVerifierStatus
  ///
  /// - Parameters:
  ///   - request: Request to send to CheckVerifierStatus.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func CheckVerifierStatus(
    _ request: Services_Trustregistry_V1_CheckVerifierStatusRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Services_Trustregistry_V1_CheckVerifierStatusRequest, Services_Trustregistry_V1_CheckVerifierStatusResponse> {
    return self.makeUnaryCall(
      path: "/services.trustregistry.v1.TrustRegistry/CheckVerifierStatus",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeCheckVerifierStatusInterceptors() ?? []
    )
  }

  /// Server streaming call to FetchData
  ///
  /// - Parameters:
  ///   - request: Request to send to FetchData.
  ///   - callOptions: Call options.
  ///   - handler: A closure called when each response is received from the server.
  /// - Returns: A `ServerStreamingCall` with futures for the metadata and status.
  public func FetchData(
    _ request: Services_Trustregistry_V1_FetchDataRequest,
    callOptions: CallOptions? = nil,
    handler: @escaping (Services_Trustregistry_V1_FetchDataResponse) -> Void
  ) -> ServerStreamingCall<Services_Trustregistry_V1_FetchDataRequest, Services_Trustregistry_V1_FetchDataResponse> {
    return self.makeServerStreamingCall(
      path: "/services.trustregistry.v1.TrustRegistry/FetchData",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeFetchDataInterceptors() ?? [],
      handler: handler
    )
  }
}

public protocol Services_Trustregistry_V1_TrustRegistryClientInterceptorFactoryProtocol {

  /// - Returns: Interceptors to use when invoking 'AddFramework'.
  func makeAddFrameworkInterceptors() -> [ClientInterceptor<Services_Trustregistry_V1_AddFrameworkRequest, Services_Trustregistry_V1_AddFrameworkResponse>]

  /// - Returns: Interceptors to use when invoking 'RemoveFramework'.
  func makeRemoveFrameworkInterceptors() -> [ClientInterceptor<Services_Trustregistry_V1_RemoveFrameworkRequest, Services_Trustregistry_V1_RemoveFrameworkResponse>]

  /// - Returns: Interceptors to use when invoking 'SearchRegistry'.
  func makeSearchRegistryInterceptors() -> [ClientInterceptor<Services_Trustregistry_V1_SearchRegistryRequest, Services_Trustregistry_V1_SearchRegistryResponse>]

  /// - Returns: Interceptors to use when invoking 'RegisterIssuer'.
  func makeRegisterIssuerInterceptors() -> [ClientInterceptor<Services_Trustregistry_V1_RegisterIssuerRequest, Services_Trustregistry_V1_RegisterIssuerResponse>]

  /// - Returns: Interceptors to use when invoking 'RegisterVerifier'.
  func makeRegisterVerifierInterceptors() -> [ClientInterceptor<Services_Trustregistry_V1_RegisterVerifierRequest, Services_Trustregistry_V1_RegisterVerifierResponse>]

  /// - Returns: Interceptors to use when invoking 'UnregisterIssuer'.
  func makeUnregisterIssuerInterceptors() -> [ClientInterceptor<Services_Trustregistry_V1_UnregisterIssuerRequest, Services_Trustregistry_V1_UnregisterIssuerResponse>]

  /// - Returns: Interceptors to use when invoking 'UnregisterVerifier'.
  func makeUnregisterVerifierInterceptors() -> [ClientInterceptor<Services_Trustregistry_V1_UnregisterVerifierRequest, Services_Trustregistry_V1_UnregisterVerifierResponse>]

  /// - Returns: Interceptors to use when invoking 'CheckIssuerStatus'.
  func makeCheckIssuerStatusInterceptors() -> [ClientInterceptor<Services_Trustregistry_V1_CheckIssuerStatusRequest, Services_Trustregistry_V1_CheckIssuerStatusResponse>]

  /// - Returns: Interceptors to use when invoking 'CheckVerifierStatus'.
  func makeCheckVerifierStatusInterceptors() -> [ClientInterceptor<Services_Trustregistry_V1_CheckVerifierStatusRequest, Services_Trustregistry_V1_CheckVerifierStatusResponse>]

  /// - Returns: Interceptors to use when invoking 'FetchData'.
  func makeFetchDataInterceptors() -> [ClientInterceptor<Services_Trustregistry_V1_FetchDataRequest, Services_Trustregistry_V1_FetchDataResponse>]
}

public final class Services_Trustregistry_V1_TrustRegistryClient: Services_Trustregistry_V1_TrustRegistryClientProtocol {
  public let channel: GRPCChannel
  public var defaultCallOptions: CallOptions
  public var interceptors: Services_Trustregistry_V1_TrustRegistryClientInterceptorFactoryProtocol?

  /// Creates a client for the services.trustregistry.v1.TrustRegistry service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Services_Trustregistry_V1_TrustRegistryClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

/// To build a server, implement a class that conforms to this protocol.
public protocol Services_Trustregistry_V1_TrustRegistryProvider: CallHandlerProvider {
  var interceptors: Services_Trustregistry_V1_TrustRegistryServerInterceptorFactoryProtocol? { get }

  /// Adds a trust registry defintion to the ecosystem
  func AddFramework(request: Services_Trustregistry_V1_AddFrameworkRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Services_Trustregistry_V1_AddFrameworkResponse>

  func RemoveFramework(request: Services_Trustregistry_V1_RemoveFrameworkRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Services_Trustregistry_V1_RemoveFrameworkResponse>

  func SearchRegistry(request: Services_Trustregistry_V1_SearchRegistryRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Services_Trustregistry_V1_SearchRegistryResponse>

  /// Registers an authoritative issuer with a credential template
  func RegisterIssuer(request: Services_Trustregistry_V1_RegisterIssuerRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Services_Trustregistry_V1_RegisterIssuerResponse>

  /// Registers an authoritative verifier with a credential template
  func RegisterVerifier(request: Services_Trustregistry_V1_RegisterVerifierRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Services_Trustregistry_V1_RegisterVerifierResponse>

  /// Removes an authoritative issuer with a credential template from the trust registry
  func UnregisterIssuer(request: Services_Trustregistry_V1_UnregisterIssuerRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Services_Trustregistry_V1_UnregisterIssuerResponse>

  /// Removes an authoritative verifier with a presentation template from the trust registry
  func UnregisterVerifier(request: Services_Trustregistry_V1_UnregisterVerifierRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Services_Trustregistry_V1_UnregisterVerifierResponse>

  func CheckIssuerStatus(request: Services_Trustregistry_V1_CheckIssuerStatusRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Services_Trustregistry_V1_CheckIssuerStatusResponse>

  func CheckVerifierStatus(request: Services_Trustregistry_V1_CheckVerifierStatusRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Services_Trustregistry_V1_CheckVerifierStatusResponse>

  func FetchData(request: Services_Trustregistry_V1_FetchDataRequest, context: StreamingResponseCallContext<Services_Trustregistry_V1_FetchDataResponse>) -> EventLoopFuture<GRPCStatus>
}

extension Services_Trustregistry_V1_TrustRegistryProvider {
  public var serviceName: Substring { return "services.trustregistry.v1.TrustRegistry" }

  /// Determines, calls and returns the appropriate request handler, depending on the request's method.
  /// Returns nil for methods not handled by this service.
  public func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "AddFramework":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Services_Trustregistry_V1_AddFrameworkRequest>(),
        responseSerializer: ProtobufSerializer<Services_Trustregistry_V1_AddFrameworkResponse>(),
        interceptors: self.interceptors?.makeAddFrameworkInterceptors() ?? [],
        userFunction: self.AddFramework(request:context:)
      )

    case "RemoveFramework":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Services_Trustregistry_V1_RemoveFrameworkRequest>(),
        responseSerializer: ProtobufSerializer<Services_Trustregistry_V1_RemoveFrameworkResponse>(),
        interceptors: self.interceptors?.makeRemoveFrameworkInterceptors() ?? [],
        userFunction: self.RemoveFramework(request:context:)
      )

    case "SearchRegistry":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Services_Trustregistry_V1_SearchRegistryRequest>(),
        responseSerializer: ProtobufSerializer<Services_Trustregistry_V1_SearchRegistryResponse>(),
        interceptors: self.interceptors?.makeSearchRegistryInterceptors() ?? [],
        userFunction: self.SearchRegistry(request:context:)
      )

    case "RegisterIssuer":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Services_Trustregistry_V1_RegisterIssuerRequest>(),
        responseSerializer: ProtobufSerializer<Services_Trustregistry_V1_RegisterIssuerResponse>(),
        interceptors: self.interceptors?.makeRegisterIssuerInterceptors() ?? [],
        userFunction: self.RegisterIssuer(request:context:)
      )

    case "RegisterVerifier":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Services_Trustregistry_V1_RegisterVerifierRequest>(),
        responseSerializer: ProtobufSerializer<Services_Trustregistry_V1_RegisterVerifierResponse>(),
        interceptors: self.interceptors?.makeRegisterVerifierInterceptors() ?? [],
        userFunction: self.RegisterVerifier(request:context:)
      )

    case "UnregisterIssuer":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Services_Trustregistry_V1_UnregisterIssuerRequest>(),
        responseSerializer: ProtobufSerializer<Services_Trustregistry_V1_UnregisterIssuerResponse>(),
        interceptors: self.interceptors?.makeUnregisterIssuerInterceptors() ?? [],
        userFunction: self.UnregisterIssuer(request:context:)
      )

    case "UnregisterVerifier":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Services_Trustregistry_V1_UnregisterVerifierRequest>(),
        responseSerializer: ProtobufSerializer<Services_Trustregistry_V1_UnregisterVerifierResponse>(),
        interceptors: self.interceptors?.makeUnregisterVerifierInterceptors() ?? [],
        userFunction: self.UnregisterVerifier(request:context:)
      )

    case "CheckIssuerStatus":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Services_Trustregistry_V1_CheckIssuerStatusRequest>(),
        responseSerializer: ProtobufSerializer<Services_Trustregistry_V1_CheckIssuerStatusResponse>(),
        interceptors: self.interceptors?.makeCheckIssuerStatusInterceptors() ?? [],
        userFunction: self.CheckIssuerStatus(request:context:)
      )

    case "CheckVerifierStatus":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Services_Trustregistry_V1_CheckVerifierStatusRequest>(),
        responseSerializer: ProtobufSerializer<Services_Trustregistry_V1_CheckVerifierStatusResponse>(),
        interceptors: self.interceptors?.makeCheckVerifierStatusInterceptors() ?? [],
        userFunction: self.CheckVerifierStatus(request:context:)
      )

    case "FetchData":
      return ServerStreamingServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Services_Trustregistry_V1_FetchDataRequest>(),
        responseSerializer: ProtobufSerializer<Services_Trustregistry_V1_FetchDataResponse>(),
        interceptors: self.interceptors?.makeFetchDataInterceptors() ?? [],
        userFunction: self.FetchData(request:context:)
      )

    default:
      return nil
    }
  }
}

public protocol Services_Trustregistry_V1_TrustRegistryServerInterceptorFactoryProtocol {

  /// - Returns: Interceptors to use when handling 'AddFramework'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeAddFrameworkInterceptors() -> [ServerInterceptor<Services_Trustregistry_V1_AddFrameworkRequest, Services_Trustregistry_V1_AddFrameworkResponse>]

  /// - Returns: Interceptors to use when handling 'RemoveFramework'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeRemoveFrameworkInterceptors() -> [ServerInterceptor<Services_Trustregistry_V1_RemoveFrameworkRequest, Services_Trustregistry_V1_RemoveFrameworkResponse>]

  /// - Returns: Interceptors to use when handling 'SearchRegistry'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeSearchRegistryInterceptors() -> [ServerInterceptor<Services_Trustregistry_V1_SearchRegistryRequest, Services_Trustregistry_V1_SearchRegistryResponse>]

  /// - Returns: Interceptors to use when handling 'RegisterIssuer'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeRegisterIssuerInterceptors() -> [ServerInterceptor<Services_Trustregistry_V1_RegisterIssuerRequest, Services_Trustregistry_V1_RegisterIssuerResponse>]

  /// - Returns: Interceptors to use when handling 'RegisterVerifier'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeRegisterVerifierInterceptors() -> [ServerInterceptor<Services_Trustregistry_V1_RegisterVerifierRequest, Services_Trustregistry_V1_RegisterVerifierResponse>]

  /// - Returns: Interceptors to use when handling 'UnregisterIssuer'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeUnregisterIssuerInterceptors() -> [ServerInterceptor<Services_Trustregistry_V1_UnregisterIssuerRequest, Services_Trustregistry_V1_UnregisterIssuerResponse>]

  /// - Returns: Interceptors to use when handling 'UnregisterVerifier'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeUnregisterVerifierInterceptors() -> [ServerInterceptor<Services_Trustregistry_V1_UnregisterVerifierRequest, Services_Trustregistry_V1_UnregisterVerifierResponse>]

  /// - Returns: Interceptors to use when handling 'CheckIssuerStatus'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeCheckIssuerStatusInterceptors() -> [ServerInterceptor<Services_Trustregistry_V1_CheckIssuerStatusRequest, Services_Trustregistry_V1_CheckIssuerStatusResponse>]

  /// - Returns: Interceptors to use when handling 'CheckVerifierStatus'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeCheckVerifierStatusInterceptors() -> [ServerInterceptor<Services_Trustregistry_V1_CheckVerifierStatusRequest, Services_Trustregistry_V1_CheckVerifierStatusResponse>]

  /// - Returns: Interceptors to use when handling 'FetchData'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeFetchDataInterceptors() -> [ServerInterceptor<Services_Trustregistry_V1_FetchDataRequest, Services_Trustregistry_V1_FetchDataResponse>]
}
